import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import SideBar from "components/SideBar"
import Header from "components/Header"
import React, { useState, useEffect } from 'react';
import Swal from 'sweetalert2'




export default function Home() {
  


  const [init, setInit] = useState(false);
  useEffect(()=>{
    if (!init) {
      Swal.fire({
        title: 'You are on DiaStu NEXT',
        text: 'A rewrite of the website, with a entirely new framework and UI.',
        icon: 'info',
        confirmButtonText: 'Cool!'
      })
     

    }
    setInit(true)
    
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
     
      <main>
        <div className='flex flex-row w-full h-full'>
          <SideBar/>
          <div className='flex-grow bg-primary h-screen fixed left-16 min-w-full right-16' >
          <div className='card'>
            <div className='card-content'>
              <h1 className='card-title' >Welcome to the Dimaverse.</h1>
              <h4 className='card-subtitle'>
                <span className="card-subtitle-word">The </span>
                <span className="delay-[40ms] card-subtitle-word ">magical </span>
                <span className="delay-[80ms] card-subtitle-word ">dimension </span>
                <span className="delay-[120ms] card-subtitle-word">where </span>
                <span className="delay-[160ms] card-subtitle-word">our </span>
                <span className="card-subtitle-word delay-[200ms]">work </span>
                <span className="card-subtitle-word delay-[240ms]">comes </span>
                <span className="card-subtitle-word delay-[280ms]">to </span>
                <span className="card-subtitle-word delay-[320ms]">life.</span>
              </h4>
            </div>
          </div>
          
          </div>
        </div>
        
      </main>
    </>
  )
  
}
