import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import SideBar from "components/SideBar"
import Header from "components/Header"
import React, { useState, useEffect } from 'react';
import Swal from 'sweetalert2'




export default function Home() {
  const [init, setInit] = useState(false);
  useEffect(()=>{
    if (!init) {
      Swal.fire({
        title: 'You are on DiaStu NEXT',
        text: 'A rewrite of the website, with a entirely new framework and UI.',
        icon: 'info',
        confirmButtonText: 'Cool!'
      })
    }
    setInit(true)
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main>
        <div className='flex'>
          <SideBar/>
          <div className='flex-grow bg-primary h-screen' >
          <Header content={<><h1 className='header m-4 font-bold'>Welcome to the <span className='text-secondary'>Dimaverse.</span></h1>
          <h5 className='text-5xl text-white m-4 font-bold'>The <span className='text-secondary'>magical</span> dimemsion where our work comes to life.</h5></>} fillscreen={false}/>
          
          </div>
        </div>
      </main>
    </>
  )
  
}
