import Head from 'next/head'

import SideBar from "components/SideBar"

import React, {useState, useEffect} from 'react';
export default function Home() {
return (
    <><Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
            <div className='flex flex-row w-full h-full font-sans'>
                <SideBar />
                <div className='flex-grow bg-primary h-full fixed left-16 right-0 -z-50 overflow-y-scroll'>
                        <div className='fancy-card-projects fancy-card group'>
                            <div className='fancy-card-content'>
                                <h1 className='fancy-fancy-card-title'>This is our work.</h1>
                                <h4 className='fancy-card-subtitle'>
                                    <span className="fancy-card-subtitle-word">The </span>
                                    <span className="delay-[50ms] fancy-card-subtitle-word">magical </span>
                                    <span className="delay-[100ms] fancy-card-subtitle-word ">dimension </span>
                                    <span className="delay-[150ms] fancy-card-subtitle-word">where </span>
                                    <span className="delay-[200ms] fancy-card-subtitle-word">our </span>
                                    <span className="fancy-card-subtitle-word delay-[250ms]">work </span>
                                    <span className="fancy-card-subtitle-word delay-[300ms]">comes </span>
                                    <span className="fancy-card-subtitle-word delay-[350ms]">to </span>
                                    <span className="fancy-card-subtitle-word delay-[400ms]">life.</span>
                                </h4>
                            </div>
                        </div>
                </div>
            </div>
    </main></>

)
}